const articleList = [
  {
    slug: 'test-markup-m5gcci',
    title: 'Test  markup',
    description: 'Test markup HTML and convert',
    body: '<dl>\n\t\t\t\t\t\t   <dt>Definition list</dt>\n\t\t\t\t\t\t   <dd>Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna\n\t\t\t\t\t\taliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea\n\t\t\t\t\t\tcommodo consequat.</dd>\n\t\t\t\t\t\t   <dt>Lorem ipsum dolor sit amet</dt>\n\t\t\t\t\t\t   <dd>Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna\n\t\t\t\t\t\taliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea\n\t\t\t\t\t\tcommodo consequat.</dd>\n\t\t\t\t\t\t</dl>',
    createdAt: '2022-01-14T18:09:53.700Z',
    updatedAt: '2022-01-14T18:09:53.700Z',
    tagList: ['HTML Markup'],
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'rosstiks1',
      image:
        'https://icdn.lenta.ru/images/2021/04/27/16/20210427163138131/square_320_c09ebae17387b7d6eeb9fa0d42afe5ee.jpg',
      following: false,
    },
  },
  {
    slug: 'title-7b9pvo',
    title: 'Title update',
    description: 'Description update',
    body: '##UPDATE\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    createdAt: '2022-01-14T16:16:57.406Z',
    updatedAt: '2022-01-14T20:27:54.020Z',
    tagList: ['test1', 'add'],
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'rosstiks1',
      image:
        'https://icdn.lenta.ru/images/2021/04/27/16/20210427163138131/square_320_c09ebae17387b7d6eeb9fa0d42afe5ee.jpg',
      following: false,
    },
  },
  {
    slug: 'cumque-consequatur-stwtnu',
    title: 'Cumque consequatur ',
    description: 'Praesentium mollitia',
    body: 'Nam accusantium perf',
    createdAt: '2022-01-14T11:01:38.266Z',
    updatedAt: '2022-01-14T11:05:47.941Z',
    tagList: ['Quia animi quos in '],
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'daydreamer',
      bio: '',
      image: 'http://not4djs.ucoz.net/_ld/276/19245024.jpg',
      following: false,
    },
  },
  {
    slug: 'hynymyma-qehy0i',
    title: 'hynymyma',
    description: 'maeaemmae',
    body: 'amey4w7,w4m m7474m7q 47m45',
    createdAt: '2022-01-14T10:34:59.253Z',
    updatedAt: '2022-01-14T11:05:49.907Z',
    tagList: ['54745', '4554h6456h4', 'h46h4'],
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'xandrnew93',
      bio: '',
      image: 'https://st2.depositphotos.com/1064024/10769/i/600/depositphotos_107694484-stock-photo-little-boy.jpg',
      following: false,
    },
  },
  {
    slug: 'in-sunt-vero-aliqua-rjrrf5',
    title: 'In sunt vero aliqua',
    description: 'Enim facilis rem con',
    body: 'Quis voluptatem qui',
    createdAt: '2022-01-13T14:07:43.429Z',
    updatedAt: '2022-01-14T11:05:56.187Z',
    tagList: ['Qui nihil qui sint q'],
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'daydreamer',
      bio: '',
      image: 'http://not4djs.ucoz.net/_ld/276/19245024.jpg',
      following: false,
    },
  },
  {
    slug: 'eligendi-non-eligend-ppro1f',
    title: 'Eligendi non eligend',
    description: 'Voluptas dolor proid',
    body: 'Dolor labore volupta',
    createdAt: '2022-01-12T06:24:57.919Z',
    updatedAt: '2022-01-14T11:05:54.331Z',
    tagList: ['Exercitationem ullam'],
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'ball',
      bio: '',
      image: 'https://pict.belvedor.com/d/25/d2555fcd91b4821152d88a093bd04336.jpg',
      following: false,
    },
  },
  {
    slug: 'impedit-aut-invento-dygvxy',
    title: 'Impedit aut invento',
    description: 'Consectetur nemo la',
    body: 'Eu voluptatem odit d',
    createdAt: '2022-01-11T14:50:29.242Z',
    updatedAt: '2022-01-14T11:22:14.993Z',
    tagList: ['Ipsum est aperiam v', 'Non ut dicta obcaeca', 'Nesciunt neque vero'],
    favorited: false,
    favoritesCount: 1,
    author: {
      username: 'walopo',
      bio: '',
      image: 'https://phonoteka.org/uploads/posts/2021-05/1621942666_24-phonoteka_org-p-drakon-art-krasivo-25.jpg',
      following: false,
    },
  },
  {
    slug: 'test-6axuu9',
    title: 'test Edit2',
    description: 'tset',
    body: 'Когда человек сознательно или интуитивно выбирает себе в жизни какую-то цель, жизненную задачу, он невольно дает себе оценку. По тому, ради чего человек живет, можно судить и о его самооценке - низкой или высокой.\nEDIT\nЕсли человек живет, чтобы приносить людям добро, облегчать их страдания, давать людям радость, то он оценивает себя на уровне этой своей человечности. Он ставит себе цель, достойную человека.\nEDIT\nТолько такая цель позволяет человеку прожить свою жизнь с достоинством и получить настоящую радость. Да, радость! Подумайте: если человек ставит себе задачей увеличивать в жизни добро, приносить людям счастье, какие неудачи могут его постигнуть? Не тому помочь? Но много ли людей не нуждаются в помощи?\n\nЕсли жить только для себя, своими мелкими заботами о собственном благополучии, то от прожитого не останется и следа. Если же жить для других, то другие сберегут то, чему служил, чему отдавал силы.\n\nМожно по-разному определять цель своего существования, но цель должна быть. Надо иметь и принципы в жизни. Одно правило в жизни должно быть у каждого человека, в его цели жизни, в его принципах жизни, в его поведении: надо прожить жизнь с достоинством, чтобы не стыдно было вспоминать.\n\nДостоинство требует доброты, великодушия, умения не быть эгоистом, быть правдивым, хорошим другом, находить радость в помощи другим.\n\nРади достоинства жизни надо уметь отказываться от мелких удовольствий и немалых тоже… Уметь извиняться, признавать перед другими ошибку - лучше, чем врать.\n\nОбманывая, человек прежде всего обманывает самого себя, ибо он думает, что успешно соврал, а люди поняли и из деликатности промолчали.\n\nЖизнь - прежде всего творчество, но это не значит, что каждый человек, чтобы жить, должен родиться художником, балериной или ученым. Можно творить просто добрую атмосферу вокруг себя. Человек может принести с собой атмосферу подозрительности, какого-то тягостного молчания, а может внести сразу радость, свет. Вот это и есть творчество.',
    createdAt: '2022-01-11T13:10:30.072Z',
    updatedAt: '2022-01-12T16:55:42.036Z',
    tagList: ['aga'],
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'walopo',
      bio: '',
      image: 'https://phonoteka.org/uploads/posts/2021-05/1621942666_24-phonoteka_org-p-drakon-art-krasivo-25.jpg',
      following: false,
    },
  },
  {
    slug: 'quibusdam-nobis-ea-v-ehi1e9',
    title: 'Quibusdam nobis ea v',
    description: 'Aperiam sed quibusda',
    body: 'Quis quaerat dolorum',
    createdAt: '2022-01-11T12:20:32.371Z',
    updatedAt: '2022-01-11T12:20:32.371Z',
    tagList: [],
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'mebuqucy',
      image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
      following: false,
    },
  },
  {
    slug: 'ut-culpa-aut-volupta-ocuky4',
    title: 'Ut culpa aut volupta',
    description: 'Deserunt repudiandae',
    body: 'Aliqua In alias nih',
    createdAt: '2022-01-11T12:18:34.140Z',
    updatedAt: '2022-01-11T12:18:34.140Z',
    tagList: ['Perferendis eiusmod '],
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'mebuqucy',
      image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
      following: false,
    },
  },
  {
    slug: 'reiciendis-omnis-asp-qy3ng6',
    title: 'Reiciendis omnis asp',
    description: 'Soluta est consecte',
    body: 'Consequatur Ipsum a',
    createdAt: '2022-01-11T12:16:49.967Z',
    updatedAt: '2022-01-11T12:16:49.967Z',
    tagList: [],
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'mebuqucy',
      image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
      following: false,
    },
  },
  {
    slug: 'similique-optio-hic-edgsu0',
    title: 'Similique optio hic',
    description: 'Est at voluptas prae',
    body: 'Quia cupidatat nihil',
    createdAt: '2022-01-11T10:50:31.004Z',
    updatedAt: '2022-01-11T13:58:14.208Z',
    tagList: ['Deserunt voluptate a'],
    favorited: false,
    favoritesCount: 1,
    author: {
      username: 'mebuqucy',
      image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
      following: false,
    },
  },
  {
    slug: 'magni-anim-non-volup-ilembg',
    title: 'Magni anim non volup',
    description: 'Laborum Facilis in ',
    body: 'Odio excepteur moles',
    createdAt: '2022-01-11T10:49:54.977Z',
    updatedAt: '2022-01-11T10:49:54.977Z',
    tagList: ['Tempore modi dicta '],
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'mebuqucy',
      image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
      following: false,
    },
  },
  {
    slug: 'quia-officia-et-iste-t7b0je',
    title: 'Quia officia et iste',
    description: 'Voluptatem Deserunt',
    body: 'Optio ad harum porr',
    createdAt: '2022-01-11T10:48:48.261Z',
    updatedAt: '2022-01-11T10:48:48.261Z',
    tagList: [],
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'mebuqucy',
      image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
      following: false,
    },
  },
  {
    slug: 'incidunt-eu-exercit-f1jhrt',
    title: 'Incidunt eu exercit',
    description: 'Voluptas ex ut autem',
    body: 'Facilis eum natus ea',
    createdAt: '2022-01-11T10:48:09.859Z',
    updatedAt: '2022-01-11T10:48:09.859Z',
    tagList: ['Consequatur providen'],
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'mebuqucy',
      image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
      following: false,
    },
  },
  {
    slug: 'adipisicing-pariatur-itxpes',
    title: 'edit33333',
    description: 'Pariatur Aute et it',
    body: 'Nihil id est dolore',
    createdAt: '2022-01-11T09:10:33.508Z',
    updatedAt: '2022-01-11T09:11:12.069Z',
    tagList: ['Illo qui nesciunt i'],
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'daydreamer',
      bio: '',
      image: 'http://not4djs.ucoz.net/_ld/276/19245024.jpg',
      following: false,
    },
  },
  {
    slug: 'culpa-id-incididunt-7vsjm4',
    title: 'Culpa id incididunt',
    description: 'In autem consectetur',
    body: 'Nisi qui beatae id a',
    createdAt: '2022-01-11T07:53:48.352Z',
    updatedAt: '2022-01-11T09:07:41.650Z',
    tagList: ['Sed est ut lorem ull'],
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'rrrab',
      bio: '',
      image: 'https://proprikol.ru/wp-content/uploads/2020/11/kartinki-raskraski-31.jpg',
      following: false,
    },
  },
  {
    slug: 'rerum-recusandae-qu-9xjmm0',
    title: 'edit',
    description: 'Laudantium voluptat',
    body: 'Molestiae consequatu',
    createdAt: '2022-01-11T07:52:02.979Z',
    updatedAt: '2022-01-11T09:06:59.124Z',
    tagList: ['Aperiam aut facere a'],
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'rrrab',
      bio: '',
      image: 'https://proprikol.ru/wp-content/uploads/2020/11/kartinki-raskraski-31.jpg',
      following: false,
    },
  },
  {
    slug: 'aut-officia-non-sunt-ecu9p1',
    title: 'EDIT',
    description: 'Ut dolore consectetu',
    body: 'Nemo dolor esse pers',
    createdAt: '2022-01-11T07:45:45.945Z',
    updatedAt: '2022-01-11T09:10:06.126Z',
    tagList: ['Qui cum alias eu cum'],
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'rrrab',
      bio: '',
      image: 'https://proprikol.ru/wp-content/uploads/2020/11/kartinki-raskraski-31.jpg',
      following: false,
    },
  },
  {
    slug: 'provident-consequat-ihmn6x',
    title: 'Provident consequat',
    description: 'Qui tenetur cum qui ',
    body: 'Inventore voluptas i',
    createdAt: '2022-01-11T07:45:25.735Z',
    updatedAt: '2022-01-11T09:07:01.530Z',
    tagList: ['Delectus consequat'],
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'rrrab',
      bio: '',
      image: 'https://proprikol.ru/wp-content/uploads/2020/11/kartinki-raskraski-31.jpg',
      following: false,
    },
  },
];
export default articleList;
